### PR TITLE
WIP: Correct expression urls

### PR DESCRIPTION
**Pull request by jdeepee**
wip start using correct ad4m expression urls for group metadata & channel names

### CODE REVIEW

**Comment by jdeepee** [comment]
This is now ready for review, I think there is still a problem with web / area links . Not sure whats going on there but I think the code could use some refactoring there generally.

**Comment by jdeepee** [comment]
The chat view seems to be working okay, I think it just needs one change where emoji targets use the url: emoji://...

Other than that it seems to be working fine

**Comment by jdeepee** [comment]
also noticed that the "hide notification indicator" console log has a concatenated version of the literal logged, not sure if this is gonna be a problem or not, was not able to test the notifications yet

**Comment by jdeepee** [comment]
Hmmm also seeing issues loading profiles in perspective-views

**Comment by fayeed** [comment]
@jdeepee Fixed the mentioned comments also now the area is a single link with literal and here's the perspective-view PR: https://github.com/fluxsocial/perspective-views/pull/44

**Pull request merged**
